import type { Metadata } from "next";

export type CalcMeta = { title: string; description: string };

const SITE = "https://semogye.com";

export const calcMeta: Record<string, CalcMeta> = {
  "business/annual-days": { title: "연차 개수 계산기 | 세모계", description: "입사일과 기준일로 근로기준법에 따라 발생하는 연차 유급휴가 일수를 계산합니다." },
  "business/annual": { title: "연차수당 계산기 | 세모계", description: "미사용 연차 일수와 통상임금으로 받을 수 있는 연차수당을 계산합니다." },
  "business/bonus": { title: "상여금·성과급 계산기 | 세모계", description: "기본급과 상여금을 합산해 실수령액을 계산합니다." },
  "business/break-even": { title: "손익분기점 계산기 | 세모계", description: "고정비와 단위 판매가·변동비를 넣으면 손익분기 판매량과 매출액을 계산합니다." },
  "business/burden": { title: "상환부담률 계산기 | 세모계", description: "월 소득 대비 대출 상환 부담 수준을 확인합니다." },
  "business/compare": { title: "알바 vs 프리랜서 비교 계산기 | 세모계", description: "시급 알바(세전)와 프리랜서 3.3% 실수령을 비교합니다." },
  "business/compound": { title: "복리 계산기 | 세모계", description: "원금과 이율, 기간을 넣으면 복리로 불어난 만기 금액을 계산합니다." },
  "business/comprehensive-tax": { title: "종합소득세 계산기 | 세모계", description: "과세표준을 넣으면 종합소득세 산출세액과 지방소득세, 총 납부세액을 계산합니다." },
  "business/corporate-tax": { title: "법인세 계산기 | 세모계", description: "과세표준을 넣으면 법인세 산출세액과 지방소득세, 총 납부세액을 바로 계산합니다." },
  "business/cost-ratio": { title: "원가율 계산기 | 세모계", description: "매출과 원가를 넣으면 원가율, 매출총이익률, 마크업률을 계산합니다." },
  "business/deposit": { title: "예금 이자 계산기 | 세모계", description: "목돈을 한 번에 맡기는 정기예금(단리)의 세후 만기 수령액을 계산합니다." },
  "business/depreciation": { title: "감가상각 계산기 | 세모계", description: "취득가액, 잔존가치, 내용연수를 넣으면 정액법 감가상각비를 계산합니다." },
  "business/discount": { title: "할인율 계산기 | 세모계", description: "정가와 판매가를 넣으면 할인액과 할인율을 바로 계산합니다." },
  "business/dismissal-advance": { title: "해고예고수당 계산기 | 세모계", description: "30일 전 해고예고가 없을 때 지급될 수 있는 해고예고수당을 계산합니다." },
  "business/dsr": { title: "DSR 계산기 | 세모계", description: "연소득과 연간 원리금상환액으로 총부채원리금상환비율(DSR)과 한도 여력을 계산합니다." },
  "business/dti": { title: "DTI 계산기 | 세모계", description: "연소득과 대출 상환액으로 총부채상환비율(DTI)과 한도 여력을 계산합니다." },
  "business/employment-insurance": { title: "고용보험료 계산기 | 세모계", description: "월급으로 고용보험료를 계산합니다." },
  "business/fee": { title: "수수료 계산기 | 세모계", description: "금액과 수수료율을 넣으면 수수료와 정산금액을 계산합니다." },
  "business/four-insurance": { title: "4대보험 계산기 | 세모계", description: "월 급여를 넣으면 국민연금·건강·장기요양·고용보험 공제액을 자동으로 나눠줍니다." },
  "business/freelance-backcalc": { title: "프리랜서 세후금액 역산 계산기 | 세모계", description: "원하는 실수령액을 입력하면 3.3% 원천징수 전 세전 계약금을 계산합니다." },
  "business/freelance": { title: "프리랜서 실수령액 계산기 | 세모계", description: "3.3% 원천징수 기준으로 실제 받는 금액을 계산합니다." },
  "business/gift-tax": { title: "증여세 계산기 | 세모계", description: "증여재산가액과 증여재산공제를 넣으면 과세표준·산출세액·납부세액을 바로 계산합니다." },
  "business/health-insurance": { title: "건강보험료 계산기 | 세모계", description: "월급으로 건강보험료와 장기요양보험료를 계산합니다." },
  "business/hourly-multi": { title: "사장님용 시급 계산기 | 세모계", description: "직원 여러 명의 시급과 근무시간을 한 번에 넣어 인건비 총액을 계산합니다." },
  "business/hourly": { title: "시급 계산기 | 세모계", description: "시급과 근무시간으로 일급·주급·월급을 빠르게 계산합니다." },
  "business/inheritance-tax": { title: "상속세 계산기 | 세모계", description: "상속재산가액과 상속공제를 넣으면 과세표준·산출세액·납부세액을 바로 계산합니다." },
  "business/inventory-turnover": { title: "재고회전율 계산기 | 세모계", description: "매출원가와 기초·기말 재고를 넣으면 재고회전율과 회전일수를 계산합니다." },
  "business/labor-cost-ratio": { title: "인건비 비율 계산기 | 세모계", description: "매출액과 인건비를 넣으면 매출 대비 인건비 비율을 바로 계산합니다." },
  "business/loan": { title: "대출 이자 계산기 | 세모계", description: "대출 원금과 이율, 기간을 넣으면 월 상환금과 총 이자를 계산합니다." },
  "business/ltv": { title: "LTV 계산기 | 세모계", description: "담보가치와 LTV 한도로 최대 대출 가능액과 담보인정비율(LTV)을 계산합니다." },
  "business/margin": { title: "마진율 계산기 | 세모계", description: "원가와 판매가를 넣으면 마진액과 마진율, 마크업률을 계산합니다." },
  "business/minimum-wage": { title: "최저임금 계산기 | 세모계", description: "2026년 최저시급 10,320원 기준으로 최저임금 충족 여부와 월급을 계산합니다." },
  "business/net-margin": { title: "순이익률 계산기 | 세모계", description: "매출, 원가, 기타비용을 넣으면 순이익과 순이익률을 계산합니다." },
  "business/net-salary": { title: "세후 실수령액 간이 계산기 | 세모계", description: "월급에서 4대보험·세금을 대략 빼고 실수령액을 확인해보세요." },
  "business/night-pay": { title: "야간수당 계산기 | 세모계", description: "야간근로 가산임금을 빠르게 계산합니다." },
  "business/ordinary-wage-reverse": { title: "통상시급 역산 계산기 | 세모계", description: "월 통상임금과 월 환산시간으로 통상시급을 역산합니다." },
  "business/ordinary-wage": { title: "통상임금 계산기 | 세모계", description: "월 통상임금과 소정근로시간으로 통상시급·통상일급을 계산합니다." },
  "business/other-income-tax": { title: "기타소득 원천징수 계산기 | 세모계", description: "강연료·원고료 등 기타소득 지급 시 떼는 원천징수 세액과 실지급액을 계산합니다." },
  "business/overtime-pay": { title: "연장근로수당 계산기 | 세모계", description: "통상시급과 연장근로시간을 넣으면 1.5배 연장근로수당을 계산합니다." },
  "business/parental-leave": { title: "육아휴직 급여 계산기 | 세모계", description: "월 통상임금과 육아휴직 기간으로 고용보험 육아휴직 급여를 계산합니다." },
  "business/pension": { title: "국민연금 계산기 | 세모계", description: "기준소득월액을 넣으면 국민연금 보험료를 계산합니다." },
  "business/prepayment-fee": { title: "중도상환수수료 계산기 | 세모계", description: "중도상환 원금, 수수료율, 잔존일수로 대출 중도상환수수료를 계산합니다." },
  "business/profit": { title: "사장님 손익 계산기 | 세모계", description: "매출에서 모든 비용을 빼고 이번 달 실제 순이익을 계산합니다." },
  "business/prorated-salary": { title: "월급 일할계산기 | 세모계", description: "중도 입사·퇴사 등으로 한 달을 다 근무하지 않았을 때 받을 월급을 일할계산합니다." },
  "business/rest-day-pay": { title: "휴일근로수당 계산기 | 세모계", description: "휴일 근로에 붙는 가산수당을 계산합니다." },
  "business/retirement-tax": { title: "퇴직소득세 계산기 | 세모계", description: "퇴직급여와 근속연수를 넣으면 퇴직소득세와 지방소득세를 계산합니다." },
  "business/retirement": { title: "퇴직금 계산기 | 세모계", description: "입사일·퇴사일과 3개월 평균임금으로 예상 퇴직금을 계산합니다." },
  "business/roe": { title: "자기자본이익률(ROE) 계산기 | 세모계", description: "당기순이익과 자기자본을 넣으면 자기자본이익률(ROE)을 계산합니다." },
  "business/roi": { title: "투자수익률(ROI) 계산기 | 세모계", description: "투자금액과 총 회수금액을 넣으면 순이익과 투자수익률(ROI)을 계산합니다." },
  "business/salary-conversion": { title: "연봉 → 월급 계산기 | 세모계", description: "연봉을 12개월 기준으로 간단히 월급으로 환산합니다." },
  "business/salary": { title: "월급 실수령액 계산기 | 세모계", description: "월급에서 4대보험과 세금을 뺀 실수령액을 계산합니다." },
  "business/savings": { title: "적금 이자 계산기 | 세모계", description: "매달 납입액과 이율, 기간을 넣으면 정기적금 만기 수령액을 계산합니다." },
  "business/selling-price-backcalc": { title: "판매가 역산 계산기 | 세모계", description: "원가와 목표 이익률을 넣으면 권장 판매가를 계산합니다." },
  "business/shutdown-allowance": { title: "휴업수당 계산기 | 세모계", description: "사용자 귀책이 아닌 휴업 시 평균임금의 70% 기준으로 휴업수당을 계산합니다." },
  "business/simplified-vat": { title: "간이과세자 부가세 계산기 | 세모계", description: "연 매출과 업종별 부가가치율로 간이과세자 부가가치세 납부세액을 계산합니다." },
  "business/supply-price": { title: "공급가액 역산 계산기 | 세모계", description: "공급가액을 넣으면 부가세와 부가세 포함 금액을 계산합니다." },
  "business/target-revenue": { title: "목표매출 계산기 | 세모계", description: "고정비, 변동비율, 목표이익으로 필요한 매출을 계산합니다." },
  "business/unemployment": { title: "실업급여 계산기 | 세모계", description: "평균임금과 나이·고용보험 가입기간으로 예상 실업급여를 계산합니다." },
  "business/vat-included": { title: "부가세 포함·제외 계산기 | 세모계", description: "부가세 포함 금액을 넣으면 공급가액과 부가세를 계산합니다." },
  "business/vat": { title: "부가세 계산기 | 세모계", description: "매출세액에서 매입세액을 빼 이번 분기 납부·환급 세액을 계산합니다." },
  "business/weekly-holiday": { title: "주휴수당 계산기 | 세모계", description: "주 15시간 이상 근무 시 발생할 수 있는 주휴수당을 계산합니다." },
  "business/withholding-33": { title: "원천세 3.3% 계산기 | 세모계", description: "프리랜서·사업소득 지급액에서 3.3%를 공제한 실수령액을 계산합니다." },
  "life/blood-pressure": { title: "혈압 계산기 | 세모계", description: "수축기·이완기 혈압을 넣으면 혈압 단계를 분류해 드려요." },
  "life/bmi": { title: "BMI 계산기 | 세모계", description: "키와 몸무게로 체질량지수를 확인해보세요." },
  "life/body-age": { title: "신체 나이 계산기 | 세모계", description: "생활 습관으로 보는 내 몸의 나이를 확인해보세요." },
  "life/body-fat": { title: "체지방률 계산기 | 세모계", description: "키·체중·나이만 넣으면 체지방률을 추정해 드려요." },
  "life/dday": { title: "D-day·기념일 계산기 | 세모계", description: "기준일부터 목표 날짜까지 며칠 남았는지 계산해드려요." },
  "life/discomfort-index": { title: "불쾌지수 계산기 | 세모계", description: "기온과 습도로 오늘의 불쾌지수를 알려드려요." },
  "life/dog-age": { title: "강아지 나이 계산기 | 세모계", description: "우리 강아지 나이를 사람 나이로 환산해 드려요." },
  "life/electricity-bill": { title: "전기요금 계산기 | 세모계", description: "한 달 사용량(kWh)만 넣으면 누진 3단계로 요금을 계산해 드려요." },
  "life/future-height": { title: "우리 아이 예상 키 계산기 | 세모계", description: "부모 키를 바탕으로 아이의 예상 키를 확인해보세요." },
  "life/grade": { title: "학점 계산기 | 세모계", description: "과목별 학점과 성적으로 평균 평점(GPA)을 계산합니다." },
  "life/kbm": { title: "키빼몸 계산기 | 세모계", description: "키에서 몸무게를 뺀 간단한 체형 지표를 확인해보세요." },
  "life/korean-age": { title: "만 나이 계산기 | 세모계", description: "생년월일을 넣으면 오늘 기준 만 나이를 바로 알려드려요." },
  "life/ovulation": { title: "배란일·가임기 계산기 | 세모계", description: "마지막 생리 시작일과 주기만 넣으면 배란일과 가임기를 알려드려요." },
  "life/percentage": { title: "퍼센트 계산기 | 세모계", description: "퍼센트 값, 비율, 증감률을 한 번에 계산해요." },
  "life/pregnancy-due-date": { title: "출산예정일 계산기 | 세모계", description: "마지막 생리 시작일만 넣으면 출산예정일과 임신 주수를 알려드려요." },
  "life/temperature": { title: "온도 변환 계산기 | 세모계", description: "섭씨·화씨·켈빈을 서로 변환해 드려요." },
  "life/waste-time": { title: "내가 날린 인생 시간 계산기 | 세모계", description: "하루 스마트폰 사용 시간이 평생 얼마가 되는지 확인해보세요." },
};

export function buildCalcMetadata(key: string): Metadata {
  const m = calcMeta[key];
  if (!m) return {};
  const url = `${SITE}/${key}`;
  return {
    title: m.title,
    description: m.description,
    alternates: { canonical: url },
    openGraph: { title: m.title, description: m.description, url, type: "website" },
    twitter: { card: "summary", title: m.title, description: m.description },
  };
}
